config/routes.rb
Rails.application.routes.draw do
  
  #devise顧客用
  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
    passwords: 'public/passwords'
  }
  
  #devise管理者用
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }
  
  #顧客用
  scope module: :public do
    root :to => 'homes#top'
    get 'about' => 'homes#about'
    resources :items, only: [:index, :show] do
      collection do
        get 'search'
      end
      
    end
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
      
    end
    resources :cart_items, except: [:new, :show, :edit] do
      collection do
        delete 'destroy_all'
      end
      
    end
    resources :orders, only: [:new, :index, :show, :create] do
      collection do
        post 'check'
        get 'complete'
      end
      
    end
    resources :addresses, except: [:new, :show]
  end
  
  #管理者用
  namespace :admin do
    root :to => 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end
  
end

app/models/item.rb
class Item < ApplicationRecord
  
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  
  has_one_attached :image
  
  with_options presence: true do
    validates :name
    validates :introduction
    validates :price
    validates :is_active, inclusion: { in: [true, false] }
  end
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  # def price_including_tax
    # (self.price * 1.1).round
  # end
  
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def index
    @items = Item.all
  end
  
  def create
    @item = Item.new(item_params)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :image)
  end
  
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<h1>Admin::Items#edit</h1>
<p>Find me in app/views/admin/items/edit.html.erb</p>
<div class="container">
  <div class="row">
    <h3>商品編集</h3>
  </div>
  <%= form_with model: @item, url: admin_item_path do |f| %>
    <div class="row offset-2 mb-3">
      <label class="col-2">商品画像</label>
       <%= f.file_field :image %>
    </div>
    <div class="row offset-2 mb-3">
      <label class="col-2">商品名</label>
      <%= f.text_field :name, size: 50, class: "col-4 p-0" %>
    </div>
    <div class="row offset-2 mb-3">
      <label class="col-2">商品説明</label>
      <%= f.text_area :introduction, class: "col-4 p-0", style: "height: 100px;" %>
    </div>
    <div class="row offset-2 mb-3">
      <label class="col-2">税抜価格</label>
      <%= f.text_field :price, class: "col-4 p-0" %>円
    </div>
    <div class="row justify-content-center">
      <%= f.submit "変更を保存", class: "btn btn-success col-2" %>
    </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<h1>Admin::Items#index</h1>
<p>Find me in app/views/admin/items/index.html.erb</p>
<div class="container">
  <div class="row justify-content-between mb-5">
    <h3 class="col-2">商品一覧</h3>
    <%= link_to new_admin_item_path do %>
      <i class="fa-solid fa-plus fa-2x fa-border btn-new-item" style="color: gray; --fa-border-radius: 100%;"></i>
    <% end %>
  </div>
  <div class="row">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
        </tr>
      </thead>
      
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td class="col-3"><%= item.id %></td>
            <td class="col-6"><%= link_to "#{item.name}", admin_item_path(item.id), class: "secondary" %></td>
            <td class="col-3"><%= item.price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/items/new.html.erb
<h1>Admin::Items#new</h1>
<p>Find me in app/views/admin/items/new.html.erb</p>
<div class="container">
  <div class="row">
    <h3>商品新規登録</h3>
  </div>
  <%= form_with model: @item, url: admin_items_path do |f| %>
    <div class="row offset-2 mb-3">
      <label class="col-2">商品画像</label>
       <%= f.file_field :image %>
    </div>
    <div class="row offset-2 mb-3">
      <label class="col-2">商品名</label>
      <%= f.text_field :name, size: 50, class: "col-4 p-0" %>
    </div>
    <div class="row offset-2 mb-3">
      <label class="col-2">商品説明</label>
      <%= f.text_area :introduction, class: "col-4 p-0", style: "height: 100px;" %>
    </div>
    <div class="row offset-2 mb-3">
      <label class="col-2">税抜価格</label>
      <%= f.text_field :price, class: "col-4 p-0" %>円
    </div>
    <div class="row justify-content-center">
      <%= f.submit "新規登録", class: "btn btn-success col-2" %>
    </div>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<h1>Admin::Items#show</h1>
<p>Find me in app/views/admin/items/show.html.erb</p>
<div class="container">
  <div class="row mb-5">
    <h3>商品詳細</h3>
  </div>
  <div class="row justify-content-center">
    <div class='col-md-3'>
      <%= image_tag @item.get_image(200, 200) %>
    </div>
    <div class='col-md-7'>
      <div class="row">
        <label class="col-2">商品名</label>
        <p class="col-5"><%= @item.name %></p>
      </div>
      <div class="row">
        <label class="col-2">商品説明</label>
        <p class="col-5"><%= @item.introduction %></p>
      </div>
      <div class="row">
        <label class="col-2">税込価格<br>
        (税抜価格)</label>
        <p class="col-3 align-self-center"><%= @item.price_including_tax.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)円</p>
      </div>
    </div>
  </div>
  <div class="row justify-content-center">
    <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-sm btn-success" %>
  </div>
</div>