config/routes.rb
Rails.application.routes.draw do
  
  #devise顧客用
  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
    passwords: 'public/passwords'
  }
  
  #devise管理者用
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }
  
  #顧客用
  scope module: :public do
    root :to => 'homes#top'
    get 'about' => 'homes#about'
    resources :items, only: [:index, :show] do
      collection do
        get 'search'
      end
      
    end
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
      
    end
    resources :cart_items, except: [:new, :show, :edit] do
      collection do
        delete 'destroy_all'
      end
      
    end
    resources :orders, only: [:new, :index, :show, :create] do
      collection do
        post 'check'
        get 'complete'
      end
      
    end
    resources :addresses, except: [:new, :show]
  end
  
  #管理者用
  namespace :admin do
    root :to => 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  with_options presence: true do
    validates :last_name
    validates :first_name
    validates :last_name_kana
    validates :first_name_kana
    validates :postal_code
    validates :address
    validates :telephone_number
    validates :is_active, inclusion: { in: [true, false] }
  end

  def full_name
    self.last_name + "  " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + "  " + self.first_name_kana
  end

  def active_for_authentication?
    super && (is_active == true)
  end


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer), notice: "会員情報を更新しました。"
    else
      render :edit
    end
  end
  
  
  def customer_params
    params.require(:customer).permit(
      :last_name, :last_name_kana,
      :first_name, :first_name_kane,
      :email, :postal_code, :address, :telephone_number, :is_active
      )
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<h1>Admin::Customers#edit</h1>
<p>Find me in app/views/admin/customers/edit.html.erb</p>
<!---------------------------------------------------------------------->
<div class="container">
  <div class="row">
    <h3><%= @customer.full_name %>さんの会員情報編集</h3>
  </div>
  <%= form_with model: @customer, url: admin_customer_path(@customer) do |f| %>
    <% render "admin/shared/error_messages", resource: @customer %>

    <div class="row">
      <label class="col-lg-3">名前</label>
      <div class="col-lg-3">
        <%= f.text_field :last_name, autoforcus: true, autocomplete: "last_name",  placeholder: "山田" %>
      </div>
      <div class="col-lg-3">
        <%= f.text_field :first_name, autoforcus: true, autocomplete: "first_name",  placeholder: "令和" %>
      </div>
    </div>

    <div class="row">
      <label class="col-lg-3">フリガナ</label>
      <div class="col-lg-3">
        <%= f.text_field :last_name_kana, autoforcus: true, autocomplete: "kana_last_name",  placeholder: "ヤマダ" %>
      </div>
      <div class="col-lg-3">
        <%= f.text_field :first_name_kana, autoforcus: true, autocomplete: "kana_first_name",  placeholder: "レイワ" %>
      </div>
    </div><br>
      
    <div class="row">
      <label class="col-lg-3">郵便番号（ハイフンなし）</label>
      <div class="col-lg-3">
        <%= f.text_field :postal_code, autoforcus: true, autocomplete: "postal_code", placeholder: "0001234" %>
      </div>
    </div><br>
      
    <div class="row">
      <label class="col-lg-3">住所</label>
      <div class="col-lg-3">
        <%= f.text_field :address, autoforcus: true, autocomplete: "address", size: 60, placeholder: "東京都港区赤坂2-11-7 WEBCAMPマンション201号室" %>
      </div>
    </div><br>
      
    <div class="row">
      <label class="col-lg-3">電話番号（ハイフンなし）</label>
      <div class="col-lg-3">
        <%= f.text_field :telephone_number, autoforcus: true, autocomplete: "telephone_number",  placeholder: "08012345678" %>
      </div>
    </div><br>

    <div class="row">
      <label class="col-lg-3">メールアドレス</label>
      <div class="col-lg-3">
        <%= f.text_field :email, autoforcus: true, autocomplete: "email",  placeholder: "sample@exanple.com" %>
      </div>
    </div><br>

    <div class="row">
      <label class="col-lg-3">会員ステータス</label>
      <div class="col-lg-3">
        <%= f.radio_button :is_active, :true %>
        <%= f.label :is_active, "有効", { value: :true } %>
        <%= f.radio_button :is_active, :false %>
        <%= f.label :is_active, "退会済み", { value: :false } %>
      </div>
    </div><br>

    <div class="row">
      <div class="col-lg-12">
        <div class="row">
          <div class="col-lg-3"></div>
          <div class="col-lg-9"><%= f.submit "変更を保存", class: "btn btn-success" %></div>
        </div>
      </div>
    </div>

  <% end %>

</div>

app/views/admin/customers/index.html.erb
<h1>Admin::Customers#index</h1>
<p>Find me in app/views/admin/customers/index.html.erb</p>
<!---------------------------------------------------------------------->
<div class="container">
  <div class="row">
    <h3>会員一覧</h3>
  </div>
  <div class="row justify-content-center">
    <table class="table table-hover col-10">
      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td class="col-1"><%= customer.id %></td>
            <td class="col-2"><%= link_to "#{customer.full_name}", admin_customer_path(customer.id), class: "secondary" %></td>
            <td class="col-2"><%= customer.email %></td>
            <td class="col-1 <%= customer.is_active ? 'text-green' : 'text-gray' %>"><%= customer.is_active ? '有効' : '退会済み' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<h1>Admin::Customers#show</h1>
<p>Find me in app/views/admin/customers/show.html.erb</p>
<!---------------------------------------------------------------------->
<div class="container">
  <div class="row">
    <h3><%= @customer.full_name %>さんの会員詳細</h3>
  </div>

  <div class="row">
    <table>
      <tbody>
        <tr>
          <th>会員ID</th><td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th><td><%= @customer.full_name %></td>
        </tr>
        <tr>
          <th>カナ</th><td><%= @customer.full_name_kana %></td>
        </tr>
        <tr>
          <th>郵便番号</th><td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th>住所</th><td><%= @customer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th><td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th><td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td class="<%= @customer.is_active ? 'text-green' : 'text-gray' %>"><%= @customer.is_active ? '有効' : '退会済み' %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="row">
    <p>注文一覧</p>
    <%= link_to "一覧を見る", admin_orders_path(@customer.id), class: "btn btn-info" %>
  </div>

  <div class="row">
    <%= link_to "編集する", edit_admin_customer_path, class: "btn btn-success" %>
  </div>

</div>