config/routes.rb
Rails.application.routes.draw do
  
  #devise顧客用
  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
    passwords: 'public/passwords'
  }
  
  #devise管理者用
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }
  
  #顧客用
  scope module: :public do
    root :to => 'homes#top'
    get 'about' => 'homes#about'
    resources :items, only: [:index, :show] do
      collection do
        get 'search'
      end
      
    end
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
      
    end
    resources :cart_items, except: [:new, :show, :edit] do
      collection do
        delete 'destroy_all'
      end
      
    end
    resources :orders, only: [:new, :index, :show, :create] do
      collection do
        post 'check'
        get 'complete'
      end
      
    end
    resources :addresses, except: [:new, :show]
  end
  
  #管理者用
  namespace :admin do
    root :to => 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  
  with_options presence: true do
    validates :customer_id
    validates :postal_code
    validates :address
    validates :name
    validates :postage
    validates :billing_amount
    validates :payment_method
    validates :order_status
  end
  
            
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { 入金待ち: 0, 入金確認: 1, 商品準備中: 2, 発送準備中:  3, 発送済: 4 }
  
  def address_display
    '〒' + postal_code + '' + address + '' + name
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def index
    
  end
 
  def show
    @order = Order.find(params[:id])
  end
  
  def update
    @order = Order.find(params[:id]) #注文詳細の特定
    @order_details = @order.order_details #注文から紐付く商品の取得
    @order.update(order_params) #注文ステータスの更新
 
 	  if @order.order_status == "入金確認" #注文ステータスが入金確認なら下の事をする
 	     @order_details.update_all(making_status: 1) #製作ステータスを「商品準備中」　更新
 	  end
  redirect_to  admin_order_path(@order) #注文詳細に遷移
  end
  
  private
  
  def order_params
    params.require(:order).permit(:order_status)
  end
  
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<h1>Admin::Orders#index</h1>
<p>Find me in app/views/admin/orders/index.html.erb</p>
<!---------------------------------------------------------------------->

app/views/admin/orders/show.html.erb
<h1>Admin::Orders#show</h1>
<p>Find me in app/views/admin/orders/show.html.erb</p>
<div class="container">
  <div class="col-sm-10"><h2>注文履歴詳細</h2></div>
  <%= form_with model: @order, url: admin_order_path, method: :patch, local: true do |f| %>
    <table class="table table-bordered">
        <tr>
          <th class="table-active" style="width:20%">購入者</th>
          <td class="link"><%= link_to admin_customer_path do %><%= @order.customer.full_name %><% end %></td>
        </tr>
        <tr><th class="table-active" style="width:20%">注文日</th><td><%= @order.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td></tr>
        <tr><th class="table-active" style="width:20%">配送先</th><td>〒<%= @order.postal_code %> <%= @order.address %> <%= @order.name %></td></tr>
        <tr><th class="table-active" style="width:20%">支払い方法</th><td><%= @order.payment_method %></td></tr>
        <tr><th class="table-active" style="width:20%"><%= f.label :order_status, "注文ステータス" %></th>
          <td>
            <% if @order.発送準備中? || @order.発送済み?  %>
              <%= f.select :order_status, Order.order_statuses.keys %>
            <% else %>
              <%= f.select :order_status, Order.order_statuses.keys, {disabled: ["発送準備中","発送済み"]} %>
            <% end %>
            <%= f.submit "更新", class: "btn btn-success" %>
          </td>
        </tr>
    </table>
  <% end %>
  <div class="row">
    <div class="col-sm-8">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th class="table-active">商品名</th>
            <th class="table-active">単価(税込)</th>
            <th class="table-active">数量</th>
            <th class="table-active">小計</th>
            <th class="table-active">製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %>
          <tr>
            <td class="align-middle"><%= order_detail.item.name %> </td>
            <td class="align-middle"><%= order_detail.price %></td>
            <td class="align-middle"><%= order_detail.amount %></td>
            <td class="align-middle"><%= order_detail.price * order_detail.amount %>円</td>
            <td class="align-middle">
              <%= form_with model: order_detail, url: admin_order_detail_path, method: :patch, local: true do |f| %>
                <%= f.hidden_field :order_detail_id, :value => order_detail.id %>
                <%= f.select :production_status, OrderDetail.production_statuses.keys %>
                <%= f.submit "更新", class: "btn btn-success" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-sm-4">
      <table class="table table-bordered">
        <tr>
          <th class="table-active" style="width:50%">商品合計</th>
          <td>
            <% @add_tax_total_payment = change_price_excluding_tax(@order.total_payment) %>
            <%= @add_tax_total_payment %>円
          </td>
        </tr>
        <tr><th class="table-active" style="width:50%">送料</th><td><%= @order.shipping_fee %>円</td></tr>
        <tr>
          <th class="table-active" style="width:50%">請求金額合計</th>
          <td>
            <% @total_payment_add_shipping_fee = @add_tax_total_payment + @order.shipping_fee %>
            <%= @total_payment_add_shipping_fee %> 円
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>