config/routes.rb
Rails.application.routes.draw do
  
  #devise顧客用
  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
    passwords: 'public/passwords'
  }
  
  #devise管理者用
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }
  
  #顧客用
  scope module: :public do
    root :to => 'homes#top'
    get 'about' => 'homes#about'
    resources :items, only: [:index, :show] do
      collection do
        get 'search'
      end
      
    end
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
      
    end
    resources :cart_items, except: [:new, :show, :edit] do
      collection do
        delete 'destroy_all'
      end
      
    end
    resources :orders, only: [:new, :index, :show, :create] do
      collection do
        post 'check'
        get 'complete'
      end
      
    end
    resources :addresses, except: [:new, :show]
  end
  
  #管理者用
  namespace :admin do
    root :to => 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end
  
end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :address
  
  with_options presence: true do
    validates :customer_id
    validates :name
    validates :postal_code
    validates :address
  end
  
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :item
  belongs_to :customer
  
  with_options presence: true do
    validates :item_id
    validates :customer_id
    validates :amount
  end
  
  
  # def subtotal
  #   item.price_including_tax * amount
  # end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  with_options presence: true do
    validates :last_name
    validates :first_name
    validates :last_name_kana
    validates :first_name_kana
    validates :postal_code
    validates :address
    validates :telephone_number
    validates :is_active, inclusion: { in: [true, false] }
  end

  def full_name
    self.last_name + "  " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + "  " + self.first_name_kana
  end

  def active_for_authentication?
    super && (is_active == true)
  end


end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items
  
  validates :name, presence: true
  
end

app/models/item.rb
class Item < ApplicationRecord
  
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  
  has_one_attached :image
  
  with_options presence: true do
    validates :name
    validates :introduction
    validates :price
    validates :is_active, inclusion: { in: [true, false] }
  end
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  # def price_including_tax
    # (self.price * 1.1).round
  # end
  
  
end

app/models/order.rb
class Order < ApplicationRecord
  
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  
  with_options presence: true do
    validates :customer_id
    validates :postal_code
    validates :address
    validates :name
    validates :postage
    validates :billing_amount
    validates :payment_method
    validates :order_status
  end
  
            
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { 入金待ち: 0, 入金確認: 1, 商品準備中: 2, 発送準備中:  3, 発送済: 4 }
  
  def address_display
    '〒' + postal_code + '' + address + '' + name
  end
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  belongs_to :item
  belongs_to :order
  
  with_options presence: true do
    validates :item_id
    validates :order_id
    validates :purchase_price
    validates :amount
    validates :making_status
  end
  
  # validates :item_id, :order_id, :purchase_price, :amount, :making_status, presence: true
  
  enum making_status: { 着手不可: 0, 商品準備中: 1, 商品梱包中: 2, 商品準備完了: 3 }
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.page(params[:page]).per(8)
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_back(fallback_location: root_path)
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  
  def genre_params
    params.require(:genre).permit(:name, :valid_invalid_status)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def index
    @items = Item.all
  end
  
  def create
    @item = Item.new(item_params)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :image)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    case resource
    when Admin
    admin_root_path
    when Customer
    root_path
    end
  end

  def after_sign_up_path_for(resource)
    case resource
    when Admin
    admin_root_path
    when Customer
    root_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
    new_admin_session_path
    else
    new_customer_session_path
    end
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :last_name, :first_name, :last_name_kana, :first_name_kana,
      :postal_code, :address, :telephone_number])
  end
  
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<nav class="navbar-dark bg-dark mt-5">
  <div class="container">
    <div class="row text-center text-xs-center text-sm-left text-md-left text-light">
      <div class="col-7">
        <h5>ONLINE STORE</h5>
        <div class="row">
          <div class="col-6">
            <ul class="list-unstyled quick-links">
              <li><%= link_to root_path, class: 'nav-link text-light mb-1' do %><i class="fa fa-angle-double-right"></i>TOP<% end %></li>
              <!--マイページへのリンクはログイン状態の時遷移するようにif文で条件分岐-->
              <% if customer_signed_in? %>
                <li><%= link_to customer_path(current_customer.id), class: 'nav-link text-light mb-1' do %><i class="fa fa-angle-double-right"></i>マイページ<% end %></li>
              <% end %>
              <li><%= link_to items_path, class: 'nav-link text-light mb-1' do %><i class="fa fa-angle-double-right"></i>商品一覧<% end %></li>
              <li><%= link_to root_path, class: 'nav-link text-light mb-1' do %><i class="fa fa-angle-double-right"></i>特定商品取引法に基づく表記<% end %></li>
              <li><%= link_to root_path, class: 'nav-link text-light mb-1' do %><i class="fa fa-angle-double-right"></i>プライバシーポリシー<% end %></li>
            </ul>
          </div>
          <div class="col-6">
            <ul class="list-unstyled quick-links">
           	  <li><%= link_to root_path, class: 'nav-link text-light mb-1' do %><i class="fa fa-angle-double-right"></i>ご利用ガイド<% end %></li>
           	<div class="footer-lists">
           	  <li><%= link_to root_path, class: 'nav-link text-light mb-1' do %><i class="fa fa-angle-double-right"></i>お支払いについて<% end %></li>
           	  <li><%= link_to root_path, class: 'nav-link text-light mb-1' do %><i class="fa fa-angle-double-right"></i>配送について<% end %></li>
           	  <li><%= link_to root_path, class: 'nav-link text-light mb-1' do %><i class="fa fa-angle-double-right"></i>よくある質問<% end %></li>
           	</div>
           </ul>
         </div>
        </div>
      </div>
      <div class="col-4">
	    <h5>ABOUT</h5>
      	  <ul class="list-unstyled quick-links">
	        <li><%= link_to about_path, class: 'nav-link text-light mb-1' do %><i class="fa fa-angle-double-right"></i>CardShop夜桜について<% end %></li>
	        <li><%= link_to root_path, class: 'nav-link text-light mb-1' do %><i class="fa fa-angle-double-right"></i>会社概要<% end %></li>
	        <li><%= link_to root_path, class: 'nav-link text-light mb-1' do %><i class="fa fa-angle-double-right"></i>メディアブレス<% end %></li>
	        <li><%= link_to root_path, class: 'nav-link text-light mb-1' do %><i class="fa fa-angle-double-right"></i>スタッフ募集<% end %></li>
	        <li><%= link_to root_path, class: 'nav-link text-light mb-1' do %><i class="fa fa-angle-double-right"></i>お問い合わせ<% end %></li>
	      </ul>
   	  </div>
	</div>
	<!--<div class="row text-xs-center text-sm-center text-md-left">-->
	<!--  <div class="col-xs-12 col-sm-12 col-md-8 mt-2 mt-sm-5">-->
	<!--    <ul class="list-unstyled list-inline social">-->
	<!-- 	  <li class="list-inline-item"><a href="#"><i class="fa fa-facebook"></i></a></li>	-->
	<!--	  <li class="list-inline-item"><a href="#"><i class="fa fa-twitter"></i></a></li>-->
	<!--	  <li class="list-inline-item"><a href="#"><i class="fa fa-instagram"></i></a></li>-->
	<!--      <li class="list-inline-item"><a href="#"><i class="fa fa-google-plus"></i></a></li>-->
	<!--      <li class="list-inline-item"><a href="#"><i class="fa fa-envelope"></i></a></li>-->
	<!--    </ul>-->
	<!--  </div>-->
	<!--  <div class="col-xs-12 col-sm-12 col-md-4 mt-2 mt-sm-5">-->
	<!--  	<p>©</p>-->
	<!--  </div>-->
	<!--<hr>-->
	<!--</div>	-->
  </div>
</nav>

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">CardShop夜桜</a>
      <!--<form class="d-flex position-relative" role="search">-->
      <!--  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
      <!--  <button class="btn btn-outline-success" type="submit">Search</button>-->
      <!--</form>-->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse position-relative" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <% if customer_signed_in? %>
            <li class="nav-item my-auto" style="color: white; align-self: center;">
              ようこそ、<%= current_customer.first_name %>さん！
            </li>
          <% end %>
          <form class="d-flex position-relative" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
          <% if customer_signed_in? %> <!--顧客ログイン時-->
            <li class="nav-item">
              <%= link_to customer_path(current_customer.id), class: 'nav-link text-light' do %>
                <i class="fa-solid fa-home"></i>
                マイページ
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to items_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-indent"></i>
                商品一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to cart_items_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-cart-shopping"></i>
                カート
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-link"></i>
                About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-sign-out-alt"></i>
                ログアウト
              <% end %>
            </li>
          <% elsif admin_signed_in? %><!--管理者ログイン時-->
            <li class="nav-item">
              <%= link_to admin_items_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-book-open"></i>
                商品一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_customers_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-book-open"></i>
                会員一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_root_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-book-open"></i>
                注文履歴一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_genres_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-book-open"></i>
                ジャンル一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-link"></i>
                About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-sign-out-alt"></i>
                ログアウト
              <% end %>
            </li>
          <% else %><!--ログインしていない時-->
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-link"></i>
                About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to items_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-home"></i>
                商品一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_customer_registration_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-user-plus"></i>
                新規登録
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_customer_session_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-sign-in-alt"></i>
                ログイン
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

<!--<nav class="navbar navbar-dark bg-dark fixed-top">-->
<!--  <div class="container-fluid">-->
<!--    <a class="navbar-brand" href="#">CardShop夜桜</a>-->
<!--    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">-->
<!--      <span class="navbar-toggler-icon"></span>-->
<!--    </button>-->
<!--    <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">-->
<!--      <div class="offcanvas-header">-->
<!--        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Dark offcanvas</h5>-->
<!--        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>-->
<!--      </div>-->
<!--      <div class="offcanvas-body">-->
<!--        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link active" aria-current="page" href="#">Home</a>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="#">Link</a>-->
<!--          </li>-->
<!--          <li class="nav-item dropdown">-->
<!--            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">-->
<!--              Dropdown-->
<!--            </a>-->
<!--            <ul class="dropdown-menu dropdown-menu-dark">-->
<!--              <li><a class="dropdown-item" href="#">Action</a></li>-->
<!--              <li><a class="dropdown-item" href="#">Another action</a></li>-->
<!--              <li>-->
<!--                <hr class="dropdown-divider">-->
<!--              </li>-->
<!--              <li><a class="dropdown-item" href="#">Something else here</a></li>-->
<!--            </ul>-->
<!--          </li>-->
<!--        </ul>-->
<!--        <form class="d-flex mt-3" role="search">-->
<!--          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
<!--          <button class="btn btn-success" type="submit">Search</button>-->
<!--        </form>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<!--</nav>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CardShop夜桜</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/4408ede51d.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <main>
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: message_type %>
      <% end %>
      <%= yield %>
    </main>

    <footer>
        <%= render "layouts/footer" %>
    </footer>
  </body>
</html>